[project]
name = "demo-scaling-identification"
version = "0.1.0"
description = "Add a short description here"
authors = ["Luc Rocher <luc@rocher.lc>"]
channels = ["conda-forge"]
platforms = ["osx-arm64"]

[tasks]

[dependencies]
matplotlib = ">=3.9.1,<3.10"
scikit-learn = ">=1.5.1,<1.6"
pandas = ">=2.2.2,<2.3"
numpy = ">=2.0.0,<2.1"
ipython = ">=8.26.0,<8.27"
ipykernel = ">=6.29.5,<6.30"
pip = ">=24.0,<25"
scipy = ">=1.14.0,<1.15"
